@startuml
:Empleado:


(introducir pedidos)
(Cancelar pedido)
(Obtener estado pedido)
(Buscar Pedidos)
(Alta cliente)
(Buscar Cliente)
(Pago con tarjeta)
(Pago en cuenta)



Empleado -- (introducir pedidos)
Empleado -- (Cancelar pedido)
Empleado --  (Obtener estado pedido)
Empleado -- (Buscar Pedidos)
Empleado -- (Alta cliente)

(Alta cliente) ..>(introducir pedidos) : <<extend>>
(introducir pedidos) ..> (Buscar Cliente) : <<include>>
(Pago con tarjeta)..> (introducir pedidos) : <<extend>>
(Cancelar pedido) ..> (Buscar Pedidos) : <<include>>
(introducir pedidos) <..(Pago en cuenta) : <<extend>>
(Obtener estado pedido) ..> (Buscar Pedidos) : <<include>>



@enduml