@startuml
:Agente:

(Evaluar Solicitud de credito)
(Solicitar informacion adicional al cliente)

(Solicitar informacion adicional al cliente) ..> (Evaluar Solicitud de credito) : <<extend>>
Agente --> (Evaluar Solicitud de credito)
@enduml